In [1]:
import numpy as np
import pandas as pd

In [2]:
# Importing the data
df = pd.read_csv('survey.csv')
df

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [3]:
# Removing the unwanted columns
df = df.drop(['comments'], axis = 1)
df = df.drop(['state'], axis = 1)
df = df.drop(['Timestamp'], axis = 1)
df = df.drop(['Country'], axis = 1)

In [4]:
df

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,NaN,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,NaN,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,NaN,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,NaN,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,No,No,Yes,NaN,26-100,No,Yes,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,f,No,No,No,NaN,100-500,Yes,Yes,No,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [5]:
df['Age'].dtype

dtype('int64')

In [6]:
df

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,NaN,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,NaN,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,NaN,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,NaN,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,No,No,Yes,NaN,26-100,No,Yes,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,f,No,No,No,NaN,100-500,Yes,Yes,No,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [7]:
count = df['self_employed'].isnull().sum()
count

18

In [8]:
count = df['Age'].isnull().sum()
count # Hence we have no missing age

0

In [9]:
count = df.isnull().sum()
count

Age                            0
Gender                         0
self_employed                 18
family_history                 0
treatment                      0
work_interfere               264
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
dtype: int64

So we have missing data in self_employed and work_interfere only

In [10]:

defaultString = 'NaN'

stringFeatures = ['self_employed','work_interfere']

for feature in stringFeatures:
        
        df[feature] = df[feature].fillna(defaultString)

In [11]:
df

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,NaN,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,NaN,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,NaN,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,NaN,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,No,No,Yes,NaN,26-100,No,Yes,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,f,No,No,No,NaN,100-500,Yes,Yes,No,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [12]:
count = df.isnull().sum()
count

Age                          0
Gender                       0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

In [13]:
# optimizing the gender column
gender = df['Gender'].str.lower()
gender = df['Gender'].unique()
gender

array(['Female', 'M', 'Male', 'male', 'female', 'm', 'Male-ish', 'maile',
       'Trans-female', 'Cis Female', 'F', 'something kinda male?',
       'Cis Male', 'Woman', 'f', 'Mal', 'Male (CIS)', 'queer/she/they',
       'non-binary', 'Femake', 'woman', 'Make', 'Nah', 'All', 'Enby',
       'fluid', 'Genderqueer', 'Female ', 'Androgyne', 'Agender',
       'cis-female/femme', 'Guy (-ish) ^_^', 'male leaning androgynous',
       'Male ', 'Man', 'Trans woman', 'msle', 'Neuter', 'Female (trans)',
       'queer', 'Female (cis)', 'Mail', 'cis male', 'A little about you',
       'Malr', 'p', 'femail', 'Cis Man',
       'ostensibly male, unsure what that really means'], dtype=object)

In [14]:
male_str = ["male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man","msle", "mail", "malr","cis man", "Cis Male", "cis male"]

trans_str = ["trans-female", "something kinda male?", "queer/she/they", "non-binary","nah", "all", "enby", "fluid", "genderqueer", "androgyne", "agender", "male leaning androgynous", "guy (-ish) ^_^", "trans woman", "neuter", "female (trans)", "queer", "ostensibly male, unsure what that really means", "A little about you", "p"]           

female_str = ["cis female", "f", "female", "woman",  "femake", "female ","cis-female/femme", "female (cis)", "femail"]

column = 'Gender'
for value in df[column]:

    if str.lower(value) in male_str:
        df['Gender'].replace(to_replace=value, value='male', inplace=True)
        
    if str.lower(value) in female_str:
        df['Gender'].replace(to_replace=value, value='female', inplace=True)
        
    if str.lower(value) in trans_str:
        df['Gender'].replace(to_replace=value, value='trans', inplace=True)
    
# Since this one value 'A little value is not replacing' so we can replace it separately.
old = 'A little about you'
new = 'trans'
cond = df[column] == old
df.loc[cond,column] = new

print(df['Gender'].unique())

['female' 'male' 'trans']

In [15]:
df

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,female,NaN,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,male,NaN,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,male,NaN,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,male,NaN,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,male,NaN,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,No,No,Yes,NaN,26-100,No,Yes,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,female,No,No,No,NaN,100-500,Yes,Yes,No,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [16]:
print(df['self_employed'].unique())

['NaN' 'Yes' 'No']

In [17]:
#Replace "NaN" string from self_employed

df['self_employed'] = df['self_employed'].replace([defaultString], 'No')
print(df['self_employed'].unique())

['No' 'Yes']

In [18]:
df

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,female,No,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,male,No,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,male,No,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,male,No,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,male,No,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,male,No,No,Yes,NaN,26-100,No,Yes,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,female,No,No,No,NaN,100-500,Yes,Yes,No,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [19]:
print(df['work_interfere'].unique())

['Often' 'Rarely' 'Never' 'Sometimes' 'NaN']

In [20]:
# Replacing the string NaN from work_interfere

df['work_interfere'] = df['work_interfere'].replace([defaultString], 'Don\'t know' )
print(df['work_interfere'].unique())

['Often' 'Rarely' 'Never' 'Sometimes' "Don't know"]

In [21]:
df.head(15)

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,female,No,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,male,No,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,male,No,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,male,No,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,male,No,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
5,33,male,No,Yes,No,Sometimes,6-25,No,Yes,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
6,35,female,No,Yes,Yes,Sometimes,1-5,Yes,Yes,No,...,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No
7,39,male,No,No,No,Never,1-5,Yes,Yes,No,...,Yes,Don't know,No,No,No,No,No,No,No,No
8,42,female,No,Yes,Yes,Sometimes,100-500,No,Yes,Yes,...,No,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No
9,23,male,No,No,No,Never,26-100,No,Yes,Don't know,...,Don't know,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No
10,31,male,No,No,Yes,Sometimes,6-25,Yes,Yes,Don't know,...,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No
11,29,male,No,No,No,Never,100-500,Yes,Yes,Don't know,...,Don't know,Don't know,No,No,Yes,Yes,Yes,Yes,Don't know,No
12,42,female,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Don't know,Somewhat difficult,Yes,Yes,Yes,Yes,Maybe,Maybe,No,Yes
13,36,male,No,Yes,No,Never,500-1000,No,Yes,Don't know,...,Don't know,Don't know,No,No,Yes,Yes,No,No,Don't know,No
14,27,male,No,No,No,Never,6-25,No,Yes,Don't know,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,Maybe,Yes,Yes,No

In [22]:
print(df['no_employees'].unique())

['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']

In [23]:
for feature in df:
    print(feature,':',df[feature].unique())

Age : [         37          44          32          31          33          35
          39          42          23          29          36          27
          46          41          34          30          40          38
          50          24          18          28          26          22
          19          25          45          21         -29          43
          56          60          54         329          55 99999999999
          48          20          57          58          47          62
          51          65          49       -1726           5          53
          61           8          11          -1          72]
Gender : ['female' 'male' 'trans']
self_employed : ['No' 'Yes']
family_history : ['No' 'Yes']
treatment : ['Yes' 'No']
work_interfere : ['Often' 'Rarely' 'Never' 'Sometimes' "Don't know"]
no_employees : ['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']
remote_work : ['No' 'Yes']
tech_company : ['Yes' 'No']
benefits : ['Yes' "Don't know" 'No']
care_options : ['Not sure' 'No' 'Yes']
wellness_program : ['No' "Don't know" 'Yes']
seek_help : ['Yes' "Don't know" 'No']
anonymity : ['Yes' "Don't know" 'No']
leave : ['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy']
mental_health_consequence : ['No' 'Maybe' 'Yes']
phys_health_consequence : ['No' 'Yes' 'Maybe']
coworkers : ['Some of them' 'No' 'Yes']
supervisor : ['Yes' 'No' 'Some of them']
mental_health_interview : ['No' 'Yes' 'Maybe']
phys_health_interview : ['Maybe' 'No' 'Yes']
mental_vs_physical : ['Yes' "Don't know" 'No']
obs_consequence : ['No' 'Yes']

**Now we have to encode the data**

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
l = LabelEncoder()

In [26]:
for feature in df:
    df[feature] = l.fit_transform(df[feature])

In [27]:
df.head(15)

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,25,0,0,0,1,2,4,0,1,2,...,2,2,1,1,1,2,1,0,2,0
1,32,1,0,0,0,3,5,0,0,0,...,0,0,0,1,0,0,1,1,0,0
2,20,1,0,0,0,3,4,0,1,1,...,0,1,1,1,2,2,2,2,1,0
3,19,1,0,1,1,2,2,0,1,1,...,1,1,2,2,1,0,0,0,1,1
4,19,1,0,0,0,1,1,1,1,2,...,0,0,1,1,1,2,2,2,0,0
5,21,1,0,1,0,4,4,0,1,2,...,0,0,1,1,2,2,1,0,0,0
6,23,0,0,1,1,4,0,1,1,1,...,1,1,0,0,1,0,1,1,0,0
7,27,1,0,0,0,1,0,1,1,1,...,2,0,1,1,0,0,1,1,1,0
8,30,0,0,1,1,4,1,0,1,2,...,1,3,0,1,2,2,1,0,1,0
9,11,1,0,0,0,1,2,0,1,0,...,0,0,1,1,2,2,0,0,2,0
10,19,1,0,0,1,4,4,1,1,0,...,0,0,1,1,1,2,1,1,0,0
11,17,1,0,0,0,1,1,1,1,0,...,0,0,1,1,2,2,2,2,0,0
12,30,0,0,1,1,4,2,0,0,2,...,0,1,2,2,2,2,0,0,1,1
13,24,1,0,1,0,1,3,0,1,0,...,0,0,1,1,2,2,1,1,0,0
14,15,1,0,0,0,1,4,0,1,0,...,0,2,1,1,1,1,0,2,2,0

In [30]:
for feature in df:
    print(feature , ':', df[feature].unique())

Age : [25 32 20 19 21 23 27 30 11 17 24 15 34 29 22 18 28 26 38 12  6 16 14 10
  7 13 33  9  1 31 43 46 41 51 42 52 36  8 44 45 35 48 39 49 37  0  3 40
 47  4  5  2 50]
Gender : [0 1 2]
self_employed : [0 1]
family_history : [0 1]
treatment : [1 0]
work_interfere : [2 3 1 4 0]
no_employees : [4 5 2 1 0 3]
remote_work : [0 1]
tech_company : [1 0]
benefits : [2 0 1]
care_options : [1 0 2]
wellness_program : [1 0 2]
seek_help : [2 0 1]
anonymity : [2 0 1]
leave : [2 0 1 3 4]
mental_health_consequence : [1 0 2]
phys_health_consequence : [1 2 0]
coworkers : [1 0 2]
supervisor : [2 0 1]
mental_health_interview : [1 2 0]
phys_health_interview : [0 1 2]
mental_vs_physical : [2 0 1]
obs_consequence : [0 1]

***Encoded Value : Actual Value***

In [29]:
# The encoded value to their respective value:

# Gender : [0 : 'female',
#           1 : 'male',
#           2 : 'trans']
    
# self_employed : [0 : 'No',
#                  1 :'Yes']
    
# family_history : [0 : 'No',
#                   1 : 'Yes']
    
# treatment : [1 : 'Yes',
#              0 : 'No']

# work_interfere = {0 : "Don't know",
#                   1 : 'Never',
#                   2 : 'Often',
#                   3 : 'Really',
#                   4 : 'Sometimes'}

# no_employees = {0 : '1-5',
#                 1 : '100-500',
#                 2 : '26-100',
#                 3 : '500-1000',
#                 4 : '6-25',
#                 5 : 'More than 1000',}

    
# remote_work : [0 : 'No',
#                1 : 'Yes']
    
# tech_company : [1 : 'Yes',
#                 0  : 'No']
    
# benefits : [2 : 'Yes',
#             0 : "Don't know",
#             1 : 'No']
    
# care_options : [1 : 'Not sure',
#                 0 : 'No',
#                 2 : 'Yes']
    
# wellness_program : [1 : 'No',
#                     0 : "Don't know",
#                     2 : 'Yes']
    
# seek_help : [2 : 'Yes',
#              0 : "Don't know",
#              1 : 'No']
    
# anonymity : [2 : 'Yes',
#              0 : "Don't know",
#              1 : 'No']
    
# leave : [2 : 'Somewhat easy',
#          0 : "Don't know",
#          1 : 'Somewhat difficult',
#          3 : 'Very difficult'
#          4 : 'Very easy']
    
# mental_health_consequence : [1 : 'No',
#                              0 : 'Maybe',
#                              2'Yes']
    
# phys_health_consequence : [1 : 'No',
#                            2 : 'Yes'
#                            0 : 'Maybe']
    
# coworkers : [1 : 'Some of them',
#              0 : 'No',
#              2 : 'Yes']
    
# supervisor : [2 : 'Yes',
#               0 : 'No',
#               1 : 'Some of them']
    
# mental_health_interview : [1 : 'No',
#                            2 : 'Yes',
#                            0 : 'Maybe']
    
# phys_health_interview : [0 : 'Maybe',
#                          1 : 'No',
#                          2 : 'Yes']
    
# mental_vs_physical : [2 : 'Yes',
#                       0 : "Don't know",
#                       1 : 'No']
    
# obs_consequence : [0 : 'No',
#                    1 : 'Yes']